name: Laravel CI

on: [push]

jobs:
  ubuntu-info:
    runs-on: ubuntu-latest

    steps:
      - name: info OS
        run: ls -al

  mac-info:
    runs-on: macos-13

    steps:
      - name: info OS
        run: ls -al
    
  laravel-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3006:3006
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7


    - name: Set Up PHP
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: '8.0.2'
        extentions: mbstring, bcmath, pdo, pdo_mysql

    - name: Install packages
      run: composer install --no-interaction

    - name: Set App
      run: cp .env.example .env

    - name: Set Key
      run: php artisan key:generate

    - name: Run test
      id: test_laravel
      run: vendor/bin/phpunit

    - name: deploy (LS)
      if: steps.test_laravel.outcome == 'success'
      run: ls

    - name: Artifact
      uses: actions/upload-artifact@v3
      if: failure()
      with: 
        name: artifacts
        path: |
          composer.json